### PR TITLE
Add monitoring heapster/influxdb/grafana addon

### PR DESCRIPTION
**Pull request by tayzlor**

### CODE REVIEW

**Comment by wallies** [comment]
is it worth adding any documentation around this?

**Comment by tayzlor** [comment]
Yep - we should have some form of docs around all addons.

**Comment by wallies** [comment]
@tayzlor do we want this anymore, as prometheus seems to be the way to go https://github.com/kubernetes/contrib/tree/master/prometheus

**Comment by tayzlor** [comment]
agreed prom should be default monitoring option. might be useful to have this in future but lets focus there first, will close this for now.

**Pull request closed without merging**
